FROM python:3.11-slim-bullseye

WORKDIR /subgen

COPY requirements.txt /subgen/requirements.txt

RUN apt-get update \
    && apt-get install -y \
        python3 \
        python3-pip \
        ffmpeg \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1

COPY *.py /subgen/

CMD [ "bash", "-c", "python3 -u launcher.py" ]
